//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mistletoe.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Template_Email_Addresses
    {
        public int ID { get; set; }
        public int TemplateID { get; set; }
        public int EmailID { get; set; }
        public bool IsSender { get; set; }
    
        public virtual Email_Address Email_Address { get; set; }
        public virtual Template Template { get; set; }
    }
}
