//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mistletoe.Web.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mistletoe.Web.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Status. Please try again!.
        /// </summary>
        public static string AdminChangeUserStatusInvalidStatus {
            get {
                return ResourceManager.GetString("AdminChangeUserStatusInvalidStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured. Please try again!.
        /// </summary>
        public static string AdminChangeUserStatusTryAgain {
            get {
                return ResourceManager.GetString("AdminChangeUserStatusTryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access denied! Please login with Admin credentials..
        /// </summary>
        public static string AdminCommonAccessDenied {
            get {
                return ResourceManager.GetString("AdminCommonAccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while fetching campaigns!.
        /// </summary>
        public static string AdminGetActiveCampaignsError {
            get {
                return ResourceManager.GetString("AdminGetActiveCampaignsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while reading global footer. Exception:.
        /// </summary>
        public static string AdminIndexError {
            get {
                return ResourceManager.GetString("AdminIndexError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while writing global footer. Exception:.
        /// </summary>
        public static string AdminSaveFooterError {
            get {
                return ResourceManager.GetString("AdminSaveFooterError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while saving global footer..
        /// </summary>
        public static string AdminSaveFooterWritingError {
            get {
                return ResourceManager.GetString("AdminSaveFooterWritingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activation failed.
        /// </summary>
        public static string CampaignChangeCampaignStatusActivationFailed {
            get {
                return ResourceManager.GetString("CampaignChangeCampaignStatusActivationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please add a template to activate a campaign.
        /// </summary>
        public static string CampaignChangeCampaignStatusAddTemplate {
            get {
                return ResourceManager.GetString("CampaignChangeCampaignStatusAddTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deactivation failed.
        /// </summary>
        public static string CampaignChangeCampaignStatusDeactivationFailed {
            get {
                return ResourceManager.GetString("CampaignChangeCampaignStatusDeactivationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Status. Please try again!.
        /// </summary>
        public static string CampaignChangeCampaignStatusInvalidStatus {
            get {
                return ResourceManager.GetString("CampaignChangeCampaignStatusInvalidStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Campaign. Please try again!.
        /// </summary>
        public static string CampaignCommonInvalidCampaign {
            get {
                return ResourceManager.GetString("CampaignCommonInvalidCampaign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template doesn&apos;t exists.\r\nPlease add a template!.
        /// </summary>
        public static string CampaignPreviewEmailNoTemplate {
            get {
                return ResourceManager.GetString("CampaignPreviewEmailNoTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload failed!\r\nPlease try again.
        /// </summary>
        public static string CampaignUploadFileError {
            get {
                return ResourceManager.GetString("CampaignUploadFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Denied!.
        /// </summary>
        public static string CommonAccessDenied {
            get {
                return ResourceManager.GetString("CommonAccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation error!&lt;br/&gt;Campaign end date cannot be less than start date..
        /// </summary>
        public static string SaveCampaignValidationError {
            get {
                return ResourceManager.GetString("SaveCampaignValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Validation error!&lt;/p&gt;&lt;p&gt;Please check the email addresses.&lt;/p&gt;.
        /// </summary>
        public static string TemplateSaveTemplateCheckEmail {
            get {
                return ResourceManager.GetString("TemplateSaveTemplateCheckEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;An error occured while saving the template!&lt;/p&gt;&lt;p&gt;Please try again.&lt;/p&gt;.
        /// </summary>
        public static string TemplateSaveTemplateTryAgain {
            get {
                return ResourceManager.GetString("TemplateSaveTemplateTryAgain", resourceCulture);
            }
        }
    }
}
