//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mistletoe.Dispatcher.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MistletoeDataEntities : DbContext
    {
        public MistletoeDataEntities()
            : base("name=MistletoeDataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Campaign> Campaign { get; set; }
        public virtual DbSet<Licensing> Licensing { get; set; }
        public virtual DbSet<Template> Template { get; set; }
    }
}
